# get all users
GET http://localhost:5000/api/user/all


### get user
GET http://localhost:5000/api/user/4


### signup
POST http://localhost:5000/api/signup
Content-Type: application/json

{
  "username": "testuser2",
  "password": "pass",
  "email": "testemail",
  "admin" : "false"
}

### login
POST http://localhost:5000/api/login
Content-Type: application/json

{
  "username": "testuser2",
  "password": "pass"
}

### create book 

POST http://localhost:5000/api/books/create
Content-Type: application/json

{
"title": "The Great Gatsbys",
"author": "F. Scott Fitzgerald",
"isbn": "978123456789s0"
}

### search book
GET http://localhost:5000/api/books?title=The%20Great%20Gatsbys


### borrow
POST http://localhost:5000/api/books/borrow
Content-Type: application/json

{
"book_id": "1",
"user_id": "2",
"issue_time": "2023-01-02T12:00:00Z",
"return_time": "2023-01-02T12:00:00Z"
}